// <auto-generated />
using System;
using GerenciadorDeCertificadosApp.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorDeCertificadosApp.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251030135947_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorDeCertificadosApp.Domain.Entities.Atividade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("ATIVIDADE", (string)null);
                });

            modelBuilder.Entity("GerenciadorDeCertificadosApp.Domain.Entities.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_EMISSAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NOME");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CERTIFICADO", (string)null);
                });

            modelBuilder.Entity("GerenciadorDeCertificadosApp.Domain.Entities.CertificadoAtividade", b =>
                {
                    b.Property<Guid>("IdCertificado")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CERTIFICADO_ID");

                    b.Property<Guid>("IdAtividade")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ATIVIDADE_ID");

                    b.HasKey("IdCertificado", "IdAtividade");

                    b.HasIndex("IdAtividade");

                    b.ToTable("CERTIFICADO_ATIVIDADE", (string)null);
                });

            modelBuilder.Entity("GerenciadorDeCertificadosApp.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("Perfil")
                        .HasColumnType("int")
                        .HasColumnName("PERFIL");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("GerenciadorDeCertificadosApp.Domain.Entities.Certificado", b =>
                {
                    b.HasOne("GerenciadorDeCertificadosApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Certificados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GerenciadorDeCertificadosApp.Domain.Entities.CertificadoAtividade", b =>
                {
                    b.HasOne("GerenciadorDeCertificadosApp.Domain.Entities.Atividade", "Atividade")
                        .WithMany("Certificados")
                        .HasForeignKey("IdAtividade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciadorDeCertificadosApp.Domain.Entities.Certificado", "Certificado")
                        .WithMany("Atividades")
                        .HasForeignKey("IdCertificado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");

                    b.Navigation("Certificado");
                });

            modelBuilder.Entity("GerenciadorDeCertificadosApp.Domain.Entities.Atividade", b =>
                {
                    b.Navigation("Certificados");
                });

            modelBuilder.Entity("GerenciadorDeCertificadosApp.Domain.Entities.Certificado", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("GerenciadorDeCertificadosApp.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Certificados");
                });
#pragma warning restore 612, 618
        }
    }
}
